# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#Minecraft/Fabric Version Info
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

#Mod Info
mod_id=ezvcsurvival
mod_name=Voiceless Survival

mod_license=All Rights Reserved
mod_version=2.0.0-beta-fabric-v2

mod_group_id=com.armilp.ezvcsurvival
mod_authors=armilp
mod_description=This mod introduces a thrilling new survival mechanic by integrating sound-based hostile mob AI. \nThe mod allows you to add custom hostile mobs that can hear and react to player voices.

#Fabric/VoiceChat Api Version
voicechat_api_version=2.5.31
voicechat_version=1.21.1-2.6.12
forge_config_api_port_version=21.1.6
fabric_version=0.116.9+1.21.1
modmenu_version=11.0.3
cobblemon_version=1.6.1+1.21.1