# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
site_debugMode = false

#Minecraft/Fabric Version Info
minecraft_version=1.18.2
yarn_mappings=1.18.2+build.4
loader_version=0.14.9

#Mod Info
mod_id=ezvcsurvival
mod_name=Voiceless Survival
mod_license=All Rights Reserved
mod_version=0.4.1
mod_group_id=com.armilp.ezvcsurvival
mod_authors=armilp
mod_description=This mod introduces a thrilling new survival mechanic by integrating sound-based hostile mob AI. \nThe mod allows you to add custom hostile mobs that can hear and react to player voices.

#Fabric/VoiceChat Api Version
voicechat_api_version=2.5.0
voicechat_version=1.18.2-2.5.0
forgeconfigapiport=3.2.4
fabric_version=0.77.0+1.18.2