plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT' apply false
    id "com.modrinth.minotaur" version "2.+" apply false
    id 'net.darkhax.curseforgegradle' version '1.1.+' apply false
}

subprojects {

    if (project.name == "modules") {
        // Skip configuring the parent `modules` project
        tasks.configureEach {
            enabled = false
        }
        return // Exit early to prevent further configuration
    }

    // Apply the Java plugin
    apply plugin: 'java'

    // Configure repositories
    repositories {
        maven { url = 'https://maven.maxhenkel.de/repository/public' }
        maven { url = 'https://maven.impactdev.net/repository/development/' }
        maven {
            name = "Fuzs Mod Resources"
            url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
        }
        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
            content {
                includeGroup "maven.modrinth"
            }
        }
        mavenCentral()
        maven {
            name = 'Sponge / Mixin'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }

    def mcVersion = project.hasProperty('minecraft_version') ? project.minecraft_version : "1.18.2"
    def targetJavaVersion = mcVersion.startsWith("1.21") ? 21 : 17

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(targetJavaVersion)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }
}

tasks.register('publicNewer-OlderPort') {
    group = "publishing"
    description = "Runs the publicModdedSite task for specific subprojects"

    // List of subprojects to include
    def targetSubprojects = ["fabric_1.18.2", "fabric_1.19.2", "fabric_1.21.1"]

    // Add dependencies for the specific subprojects
    dependsOn subprojects.findAll { subproject ->
        targetSubprojects.contains(subproject.name)
    }.collect { subproject ->
        ":${subproject.path}:publicModdedSite"
    }
}
