pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Sponge Snapshots'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }
}


rootProject.name = 'Voiceless Survival'

// === FABRIC ===
//include "modules:fabric_1.21.4"
//include "modules:fabric_1.21.5"
include "modules:fabric_1.21.8"
// ----------

