pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Sponge Snapshots'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }
}


rootProject.name = 'Voiceless Survival'

// === FABRIC ===
include "modules:fabric_1.18.2"
include "modules:fabric_1.19.2"
include "modules:fabric_1.20.1"
include "modules:fabric_1.21.1"
include "modules:fabric_1.21.4"
// ----------

