# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#Minecraft/Fabric Version Info
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

#Mod Info
mod_id=ezvcsurvival
mod_name=Voiceless Survival
mod_license=All Rights Reserved
mod_version=0.6.2
mod_group_id=com.armilp.ezvcsurvival
mod_authors=armilp
mod_description=This mod introduces a thrilling new survival mechanic by integrating sound-based hostile mob AI. \nThe mod allows you to add custom hostile mobs that can hear and react to player voices.

#Fabric/VoiceChat Api Version
voicechat_api_version=2.5.27
voicechat_version=1.21.4-2.5.27
forgeconfigapiport=21.4.1
fabric_version=0.114.3+1.21.4